// <auto-generated />
using FOS_ISLAND_BBQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FOS_ISLAND_BBQ.Migrations.FOS_ISLAND_BBQMenu
{
    [DbContext(typeof(FOS_ISLAND_BBQMenuContext))]
    [Migration("20210127065502_UploadBls")]
    partial class UploadBls
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FOS_ISLAND_BBQ.Models.MenuModel", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("imageURL");

                    b.Property<string>("name");

                    b.Property<string>("price");

                    b.HasKey("id");

                    b.ToTable("MenuModel");
                });

            modelBuilder.Entity("FOS_ISLAND_BBQ.Models.UploadAdveristment", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("imageURL");

                    b.HasKey("id");

                    b.ToTable("UploadAdveristment");
                });

            modelBuilder.Entity("FOS_ISLAND_BBQ.Models.UploadBills", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("imageURL");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("UploadBills");
                });
#pragma warning restore 612, 618
        }
    }
}
